export const breedCodes = [
    {
        breed: '01',
        breed_Lit: 'Holstein (UK)',
        dairyCouncilGroup: 'Holstein',
        bcmsBreedCode: 'HF',
        dardBreedCode: 'HOL',
    },
    {
        breed: '02',
        breed_Lit: 'Dairy Shorthorn (UK)',
        dairyCouncilGroup: 'Shorthorn',
        bcmsBreedCode: 'DS',
        dardBreedCode: 'SHD',
    },
    {
        breed: '03',
        breed_Lit: 'Ayrshire (UK)',
        dairyCouncilGroup: 'Ayrshire',
        bcmsBreedCode: 'AY',
        dardBreedCode: 'AYR',
    },
    {
        breed: '04',
        breed_Lit: 'Jersey (mainland)',
        dairyCouncilGroup: 'Jersey',
        bcmsBreedCode: 'JE',
        dardBreedCode: 'JER',
    },
    {
        breed: '05',
        breed_Lit: 'Guernsey (mainland)',
        dairyCouncilGroup: 'Guernsey',
        bcmsBreedCode: 'GU',
        dardBreedCode: 'GU',
    },
    {
        breed: '06',
        breed_Lit: 'South Devon',
        dairyCouncilGroup: 'Others',
        bcmsBreedCode: 'SD',
        dardBreedCode: null,
    },
    {
        breed: '07',
        breed_Lit: 'Red Poll',
        dairyCouncilGroup: 'Red Poll',
        bcmsBreedCode: 'RP',
        dardBreedCode: 'RPL',
    },
    {
        breed: '08',
        breed_Lit: 'Welsh Black',
        dairyCouncilGroup: 'Others',
        bcmsBreedCode: 'WB',
        dardBreedCode: null,
    },
    {
        breed: '09',
        breed_Lit: 'Lincoln Red',
        dairyCouncilGroup: 'Others',
        bcmsBreedCode: 'LR',
        dardBreedCode: 'LNR',
    },
    {
        breed: '10',
        breed_Lit: 'Dexter/Kerry',
        dairyCouncilGroup: 'Kerry',
        bcmsBreedCode: 'KE',
        dardBreedCode: 'KE',
    },
    {
        breed: '11',
        breed_Lit: 'Ancient White Cattle',
        dairyCouncilGroup: 'Others',
        bcmsBreedCode: null,
        dardBreedCode: null,
    },
    {
        breed: '12',
        breed_Lit: 'British Holstein',
        dairyCouncilGroup: 'Holstein',
        bcmsBreedCode: 'HF',
        dardBreedCode: 'HOL',
    },
    {
        breed: '13',
        breed_Lit: 'NZ/Aus Shorthorn',
        dairyCouncilGroup: 'Shorthorn',
        bcmsBreedCode: 'DS',
        dardBreedCode: 'SH',
    },
    {
        breed: '14',
        breed_Lit: 'Red & White Ayrshire',
        dairyCouncilGroup: 'Ayrshire',
        bcmsBreedCode: 'AY',
        dardBreedCode: 'AYR',
    },
    {
        breed: '15',
        breed_Lit: 'Red & White Friesian',
        dairyCouncilGroup: 'Holstein',
        bcmsBreedCode: 'BF',
        dardBreedCode: 'FR',
    },
    {
        breed: '16',
        breed_Lit: 'Devon',
        dairyCouncilGroup: 'Others',
        bcmsBreedCode: 'DEV',
        dardBreedCode: null,
    },
    {
        breed: '17',
        breed_Lit: 'Danish Red',
        dairyCouncilGroup: 'Danish Red',
        bcmsBreedCode: 'DR',
        dardBreedCode: 'DR',
    },
    {
        breed: '18',
        breed_Lit: 'Charolais',
        dairyCouncilGroup: 'Others',
        bcmsBreedCode: 'CH',
        dardBreedCode: 'CH',
    },
    {
        breed: '19',
        breed_Lit: 'Hereford',
        dairyCouncilGroup: 'Others',
        bcmsBreedCode: 'HE',
        dardBreedCode: 'HER',
    },
    {
        breed: '20',
        breed_Lit: 'British Friesian',
        dairyCouncilGroup: 'Holstein',
        bcmsBreedCode: 'BF',
        dardBreedCode: 'FR',
    },
    {
        breed: '21',
        breed_Lit: 'Aberdeen Angus',
        dairyCouncilGroup: 'Others',
        bcmsBreedCode: 'AA',
        dardBreedCode: 'AA',
    },
    {
        breed: '22',
        breed_Lit: 'British Dane',
        dairyCouncilGroup: 'Brit Dane',
        bcmsBreedCode: 'DS',
        dardBreedCode: null,
    },
    {
        breed: '23',
        breed_Lit: 'Simmetal/Fleckvieh',
        dairyCouncilGroup: 'Others',
        bcmsBreedCode: 'SM',
        dardBreedCode: 'SIM',
    },
    {
        breed: '24',
        breed_Lit: 'Meuse-Rhine-Issel',
        dairyCouncilGroup: 'MRI',
        bcmsBreedCode: 'MRI',
        dardBreedCode: 'MRI',
    },
    {
        breed: '25',
        breed_Lit: "Blonde D'Aquitaine",
        dairyCouncilGroup: 'Others',
        bcmsBreedCode: 'BA',
        dardBreedCode: 'DAQ',
    },
    {
        breed: '26',
        breed_Lit: 'Main Anjou',
        dairyCouncilGroup: 'Maine Anj',
        bcmsBreedCode: 'MA',
        dardBreedCode: 'MAJ',
    },
    {
        breed: '27',
        breed_Lit: 'Other Cattle',
        dairyCouncilGroup: 'Others',
        bcmsBreedCode: null,
        dardBreedCode: null,
    },
    {
        breed: '28',
        breed_Lit: 'Montbeliarde',
        dairyCouncilGroup: 'Montebel.',
        bcmsBreedCode: 'MO',
        dardBreedCode: 'MB',
    },
    {
        breed: '29',
        breed_Lit: 'Breed Not Known ',
        dairyCouncilGroup: 'Others',
        bcmsBreedCode: null,
        dardBreedCode: null,
    },
    {
        breed: '30',
        breed_Lit: 'Gloucester',
        dairyCouncilGroup: 'Glouces.',
        bcmsBreedCode: 'GL',
        dardBreedCode: 'GLO',
    },
    {
        breed: '31',
        breed_Lit: 'Brown Swiss',
        dairyCouncilGroup: 'B Swiss',
        bcmsBreedCode: 'BS',
        dardBreedCode: 'SBR',
    },
    {
        breed: '32',
        breed_Lit: 'Sussex',
        dairyCouncilGroup: 'Others',
        bcmsBreedCode: 'SU',
        dardBreedCode: null,
    },
    {
        breed: '33',
        breed_Lit: 'Limousin',
        dairyCouncilGroup: 'Others',
        bcmsBreedCode: 'LIM',
        dardBreedCode: null,
    },
    {
        breed: '34',
        breed_Lit: 'Murray Grey',
        dairyCouncilGroup: 'Others',
        bcmsBreedCode: 'MG',
        dardBreedCode: null,
    },
    {
        breed: '35',
        breed_Lit: 'Gelbvieh',
        dairyCouncilGroup: 'Others',
        bcmsBreedCode: 'GE',
        dardBreedCode: 'GE',
    },
    {
        breed: '36',
        breed_Lit: 'Normande',
        dairyCouncilGroup: 'Normande',
        bcmsBreedCode: 'NO',
        dardBreedCode: 'NOR',
    },
    {
        breed: '37',
        breed_Lit: 'British Blue',
        dairyCouncilGroup: 'Others',
        bcmsBreedCode: 'BRB',
        dardBreedCode: 'BB',
    },
    {
        breed: '38',
        breed_Lit: 'Beef Shorthorn',
        dairyCouncilGroup: 'Others',
        bcmsBreedCode: 'BSH',
        dardBreedCode: null,
    },
    {
        breed: '39',
        breed_Lit: 'Chianina',
        dairyCouncilGroup: 'Others',
        bcmsBreedCode: 'CHI',
        dardBreedCode: null,
    },
    {
        breed: '40',
        breed_Lit: 'European Shorthorn',
        dairyCouncilGroup: 'Shorthorn',
        bcmsBreedCode: 'DS',
        dardBreedCode: 'SH',
    },
    {
        breed: '41',
        breed_Lit: 'Longhorn',
        dairyCouncilGroup: 'Others',
        bcmsBreedCode: 'LH',
        dardBreedCode: null,
    },
    {
        breed: '42',
        breed_Lit: 'European Water Buffalo',
        dairyCouncilGroup: 'Others',
        bcmsBreedCode: 'BU',
        dardBreedCode: null,
    },
    {
        breed: '43',
        breed_Lit: 'Czech Holstein Friesian',
        dairyCouncilGroup: 'Holstein',
        bcmsBreedCode: 'HF',
        dardBreedCode: 'HOL',
    },
    {
        breed: '44',
        breed_Lit: 'Romagnola',
        dairyCouncilGroup: 'Others',
        bcmsBreedCode: 'RO',
        dardBreedCode: null,
    },
    {
        breed: '45',
        breed_Lit: 'Galloway',
        dairyCouncilGroup: 'Others',
        bcmsBreedCode: 'GA',
        dardBreedCode: null,
    },
    {
        breed: '46',
        breed_Lit: 'Irish Holstein Friesian',
        dairyCouncilGroup: 'Holstein',
        bcmsBreedCode: 'HF',
        dardBreedCode: 'HOL',
    },
    {
        breed: '47',
        breed_Lit: 'Australian Holstein Friesian',
        dairyCouncilGroup: 'Holstein',
        bcmsBreedCode: 'HF',
        dardBreedCode: 'HOL',
    },
    {
        breed: '48',
        breed_Lit: 'Polish Holstein Friesian',
        dairyCouncilGroup: 'Others',
        bcmsBreedCode: 'HF',
        dardBreedCode: 'HOL',
    },
    {
        breed: '49',
        breed_Lit: 'Angler',
        dairyCouncilGroup: 'Glamorgan',
        bcmsBreedCode: null,
        dardBreedCode: null,
    },
    {
        breed: '50',
        breed_Lit: 'Shetland',
        dairyCouncilGroup: 'Shetland',
        bcmsBreedCode: 'SH',
        dardBreedCode: 'STL',
    },
    {
        breed: '51',
        breed_Lit: 'Blue Albion',
        dairyCouncilGroup: 'Others',
        bcmsBreedCode: 'BAL',
        dardBreedCode: null,
    },
    {
        breed: '52',
        breed_Lit: 'Swedish Holstein Friesian',
        dairyCouncilGroup: 'Holstein',
        bcmsBreedCode: 'SRW',
        dardBreedCode: 'SWR',
    },
    {
        breed: '53',
        breed_Lit: 'Rotbunte',
        dairyCouncilGroup: 'Others',
        bcmsBreedCode: null,
        dardBreedCode: null,
    },
    {
        breed: '54',
        breed_Lit: 'Spanish Holstein Friesian',
        dairyCouncilGroup: 'Holstein',
        bcmsBreedCode: 'HF',
        dardBreedCode: 'HOL',
    },
    {
        breed: '55',
        breed_Lit: 'Piemontese',
        dairyCouncilGroup: 'Others',
        bcmsBreedCode: 'PI',
        dardBreedCode: 'PIE',
    },
    {
        breed: '56',
        breed_Lit: 'Salers',
        dairyCouncilGroup: 'Others',
        bcmsBreedCode: 'SA',
        dardBreedCode: null,
    },
    {
        breed: '57',
        breed_Lit: 'Highland/Luing',
        dairyCouncilGroup: 'Others',
        bcmsBreedCode: 'HI',
        dardBreedCode: null,
    },
    {
        breed: '58',
        breed_Lit: 'Irish Moiled',
        dairyCouncilGroup: 'Irish Mol.',
        bcmsBreedCode: 'IM',
        dardBreedCode: 'IM',
    },
    {
        breed: '59',
        breed_Lit: 'Swedish Red',
        dairyCouncilGroup: 'Scan. Red',
        bcmsBreedCode: 'SH',
        dardBreedCode: null,
    },
    {
        breed: '60',
        breed_Lit: 'German  Holstein Friesian',
        dairyCouncilGroup: 'Holstein',
        bcmsBreedCode: 'HF',
        dardBreedCode: 'HOL',
    },
    {
        breed: '61',
        breed_Lit: 'Danish  Holstein Friesian',
        dairyCouncilGroup: 'Holstein',
        bcmsBreedCode: 'HF',
        dardBreedCode: 'HOL',
    },
    {
        breed: '62',
        breed_Lit: 'New Zealand  Holstein Friesian',
        dairyCouncilGroup: 'Holstein',
        bcmsBreedCode: 'HF',
        dardBreedCode: 'HOL',
    },
    {
        breed: '63',
        breed_Lit: 'Dutch  Holstein Friesian',
        dairyCouncilGroup: 'Holstein',
        bcmsBreedCode: 'HF',
        dardBreedCode: 'HOL',
    },
    {
        breed: '64',
        breed_Lit: 'Canadian  Holstein Friesian',
        dairyCouncilGroup: 'Holstein',
        bcmsBreedCode: 'HF',
        dardBreedCode: 'HOL',
    },
    {
        breed: '65',
        breed_Lit: 'American  Holstein Friesian',
        dairyCouncilGroup: 'Holstein',
        bcmsBreedCode: 'HF',
        dardBreedCode: 'HOL',
    },
    {
        breed: '66',
        breed_Lit: 'European Jersey',
        dairyCouncilGroup: 'Jersey',
        bcmsBreedCode: 'JE',
        dardBreedCode: 'JER',
    },
    {
        breed: '67',
        breed_Lit: 'North American Guernsey',
        dairyCouncilGroup: 'Guernsey',
        bcmsBreedCode: 'GU',
        dardBreedCode: 'GU',
    },
    {
        breed: '68',
        breed_Lit: 'NZ/Aus. Jersey',
        dairyCouncilGroup: 'Jersey',
        bcmsBreedCode: 'JE',
        dardBreedCode: 'JER',
    },
    {
        breed: '69',
        breed_Lit: 'N American Shorthorn',
        dairyCouncilGroup: 'Shorthorn',
        bcmsBreedCode: 'DS',
        dardBreedCode: 'SH',
    },
    {
        breed: '70',
        breed_Lit: 'N.American Ayrshire',
        dairyCouncilGroup: 'Ayrshire',
        bcmsBreedCode: 'AY',
        dardBreedCode: 'AYR',
    },
    {
        breed: '71',
        breed_Lit: 'French  Holstein Friesian',
        dairyCouncilGroup: 'Holstein',
        bcmsBreedCode: 'HF',
        dardBreedCode: 'HOL',
    },
    {
        breed: '72',
        breed_Lit: 'Italian  Holstein Friesian',
        dairyCouncilGroup: 'Holstein',
        bcmsBreedCode: 'HF',
        dardBreedCode: 'HOL',
    },
    {
        breed: '73',
        breed_Lit: 'Finnish Ayrshire',
        dairyCouncilGroup: 'Ayrshire',
        bcmsBreedCode: 'AY',
        dardBreedCode: 'AYR',
    },
    {
        breed: '74',
        breed_Lit: 'Island Jersey',
        dairyCouncilGroup: 'Jersey',
        bcmsBreedCode: 'JE',
        dardBreedCode: 'JER',
    },
    {
        breed: '75',
        breed_Lit: 'Island Guernsey',
        dairyCouncilGroup: 'Guernsey',
        bcmsBreedCode: 'GU',
        dardBreedCode: 'GU',
    },
    {
        breed: '76',
        breed_Lit: 'North American Jersey',
        dairyCouncilGroup: 'Jersey',
        bcmsBreedCode: 'JE',
        dardBreedCode: 'JER',
    },
    {
        breed: '77',
        breed_Lit: 'Norwegian Red/ Ayrshire',
        dairyCouncilGroup: 'Ayrshire',
        bcmsBreedCode: 'NR',
        dardBreedCode: 'AYR',
    },
    {
        breed: '78',
        breed_Lit: 'NZ/ Aus Ayrshire',
        dairyCouncilGroup: 'Ayrshire',
        bcmsBreedCode: 'AY',
        dardBreedCode: 'AYR',
    },
    {
        breed: '79',
        breed_Lit: 'NZ/ Aus Guernsey',
        dairyCouncilGroup: 'Guernsey',
        bcmsBreedCode: 'GU',
        dardBreedCode: 'GU',
    },
    {
        breed: 'A1',
        breed_Lit: 'USA Brown Swiss',
        dairyCouncilGroup: 'B Swiss',
        bcmsBreedCode: 'BS',
        dardBreedCode: 'SBR',
    },
    {
        breed: 'AA',
        breed_Lit: 'Aberdeen Angus ',
        dairyCouncilGroup: 'Others',
        bcmsBreedCode: 'AA',
        dardBreedCode: 'AA',
    },
    {
        breed: 'AS',
        breed_Lit: 'Australian Angus',
        dairyCouncilGroup: 'Others',
        bcmsBreedCode: 'AA',
        dardBreedCode: 'AA',
    },
    {
        breed: 'AU',
        breed_Lit: 'Australian Brown Swiss',
        dairyCouncilGroup: 'B Swiss',
        bcmsBreedCode: 'BS',
        dardBreedCode: 'SBR',
    },
    {
        breed: 'B ',
        breed_Lit: 'Belgian Blue',
        dairyCouncilGroup: 'Others',
        bcmsBreedCode: 'BRB',
        dardBreedCode: 'BB',
    },
    {
        breed: 'C1',
        breed_Lit: 'Canadian Brown Swiss',
        dairyCouncilGroup: 'B Swiss',
        bcmsBreedCode: 'BS',
        dardBreedCode: 'SBR',
    },
    {
        breed: 'CA',
        breed_Lit: 'Canadian Angus',
        dairyCouncilGroup: 'Others',
        bcmsBreedCode: 'AA',
        dardBreedCode: 'AA',
    },
    {
        breed: 'D ',
        breed_Lit: 'Danish Belgian Blue',
        dairyCouncilGroup: 'Others',
        bcmsBreedCode: 'BRB',
        dardBreedCode: 'BB',
    },
    {
        breed: 'D1',
        breed_Lit: 'Dutch Brown Swiss',
        dairyCouncilGroup: 'B Swiss',
        bcmsBreedCode: 'BS',
        dardBreedCode: 'SBR',
    },
    {
        breed: 'E ',
        breed_Lit: 'Estonian Holstein',
        dairyCouncilGroup: 'Holstein',
        bcmsBreedCode: 'HF',
        dardBreedCode: 'HOL',
    },
    {
        breed: 'E1',
        breed_Lit: 'Spanish Brown Swiss',
        dairyCouncilGroup: 'B Swiss',
        bcmsBreedCode: 'BS',
        dardBreedCode: 'SBR',
    },
    {
        breed: 'EA',
        breed_Lit: 'European Angus',
        dairyCouncilGroup: 'Others',
        bcmsBreedCode: 'AA',
        dardBreedCode: 'AA',
    },
    {
        breed: 'F1',
        breed_Lit: 'French Brown Swiss',
        dairyCouncilGroup: 'B Swiss',
        bcmsBreedCode: 'BS',
        dardBreedCode: 'SBR',
    },
    {
        breed: 'G1',
        breed_Lit: 'German Brown Swiss',
        dairyCouncilGroup: 'B Swiss',
        bcmsBreedCode: 'BS',
        dardBreedCode: 'SBR',
    },
    {
        breed: 'H ',
        breed_Lit: 'Belgian Blue',
        dairyCouncilGroup: 'Others',
        bcmsBreedCode: 'BRB',
        dardBreedCode: 'BB',
    },
    {
        breed: 'I ',
        breed_Lit: 'Imported Belgian Blue',
        dairyCouncilGroup: 'Others',
        bcmsBreedCode: 'BRB',
        dardBreedCode: 'BB',
    },
    {
        breed: 'IR',
        breed_Lit: 'Irish Angus',
        dairyCouncilGroup: 'Others',
        bcmsBreedCode: 'AA',
        dardBreedCode: 'AA',
    },
    {
        breed: 'IT',
        breed_Lit: 'Italian Brown Swiss',
        dairyCouncilGroup: 'B Swiss',
        bcmsBreedCode: 'BS',
        dardBreedCode: 'SBR',
    },
    {
        breed: 'LI',
        breed_Lit: 'Limousin',
        dairyCouncilGroup: 'Others',
        bcmsBreedCode: 'LIM',
        dardBreedCode: 'LIM',
    },
    {
        breed: 'NZ',
        breed_Lit: 'New Zealand Angus',
        dairyCouncilGroup: 'Others',
        bcmsBreedCode: 'AA',
        dardBreedCode: 'AA',
    },
    {
        breed: 'P ',
        breed_Lit: 'Polled',
        dairyCouncilGroup: 'Others',
        bcmsBreedCode: null,
        dardBreedCode: null,
    },
    {
        breed: 'RO',
        breed_Lit: 'Romanian Brown Swiss',
        dairyCouncilGroup: 'B Swiss',
        bcmsBreedCode: 'BS',
        dardBreedCode: 'SBR',
    },
    {
        breed: 'SW',
        breed_Lit: 'Swiss Brown Swiss',
        dairyCouncilGroup: 'B Swiss',
        bcmsBreedCode: 'BS',
        dardBreedCode: 'SBR',
    },
    {
        breed: 'US',
        breed_Lit: 'North American Angus',
        dairyCouncilGroup: 'Others',
        bcmsBreedCode: 'AA',
        dardBreedCode: 'AA',
    },
    {
        breed: 'X ',
        breed_Lit: 'Belgian Blue',
        dairyCouncilGroup: 'Others',
        bcmsBreedCode: 'BRB',
        dardBreedCode: 'BB',
    },
    {
        breed: 'Z ',
        breed_Lit: 'Non-Pedigree / Dead',
        dairyCouncilGroup: 'Holstein',
        bcmsBreedCode: null,
        dardBreedCode: null,
    },
];
export default breedCodes;
